#! /bin/bash 

#####
# Load bgenix module here

# e.g. Broad institute
source /broad/software/scripts/useuse
use GCC-5.2
use .bgen-1.0

CHROM=$SGE_TASK_ID
UKBB_PATH=$1
WORK_DIR=$2

# MAF >= 0.05 and INFO >= 0.4 and not indel
cat $UKBB_PATH/ukb_mfi_chr${CHROM}_v3.txt | awk '{ if (($6 >= 0.05) && ($8 >= 0.4) && (length($4) == 1) && (length($5) == 1)) { print $2 } }' | sort -u > $WORK_DIR/chrom${CHROM}.rsids.incl

bgenix -g $UKBB_PATH/ukb_imp_chr${CHROM}_v3.bgen -incl-rsids $WORK_DIR/chrom${CHROM}.rsids.incl > $WORK_DIR/chrom$CHROM.bgen

cat $UKBB_PATH/ukb_mfi_chr${CHROM}_v3.txt | grep -w -F -f $WORK_DIR/chrom$CHROM.rsids.incl > $WORK_DIR/chrom$CHROM.ukb_mfi.txt
