###
# ADD CODES TO LOAD R MODULE HERE
###

# nps_decor.job
Rscript npsR/nps_decor.R $1 $SGE_TASK_ID $2 > $1/log/nps_decor.Rout.$2.$SGE_TASK_ID

logfile="$1/log/nps_decor.Rout.$2.$SGE_TASK_ID"

if [ ! -f $logfile ]; then
    "nps_decor FAILED: STOP"
    exit 1
fi
	
last=`tail -n 1 $logfile`

if [ "$last" != "Done" ]; then
    "nps_decor FAILED: STOP"
    exit 1
fi

# nps_prune.job
Rscript npsR/nps_prune.R $1 $SGE_TASK_ID $2 > $1/log/nps_prune.Rout.$2.$SGE_TASK_ID

logfile="$1/log/nps_prune.Rout.$2.$SGE_TASK_ID"

if [ ! -f $logfile ]; then
    "nps_prune FAILED: STOP"
    exit 1
fi
	
last=`tail -n 1 $logfile`

if [ "$last" != "Done" ]; then
    "nps_prune FAILED: STOP"
    exit 1
fi

# nps_gwassig.job
if [ $2 -eq "0" ]
then 
    rm -vf $1/win.$SGE_TASK_ID.*.pruned.tailfix.table
    rm -vf $1/trPT.$SGE_TASK_ID.tail.RDS
    rm -vf $1/tail_betahat.$SGE_TASK_ID.table
else 
    rm -vf $1/win_$2.$SGE_TASK_ID.*.pruned.tailfix.table
fi

Rscript npsR/nps_gwassig.R $1 $SGE_TASK_ID $2 > $1/log/nps_gwassig.Rout.$2.$SGE_TASK_ID
